# Generated by Django 3.1.2 on 2020-10-31 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0004_auto_20201031_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
