# Generated by Django 3.1.2 on 2020-11-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20201031_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriberregistration',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='subscriberregistration',
            name='pricing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plan.plan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
