# Generated by Django 3.1.2 on 2020-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
