# Generated by Django 3.1.2 on 2020-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20201101_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberregistration',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
