# Generated by Django 3.1.2 on 2020-10-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201029_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='ratings',
            index_together=set(),
        ),
    ]
